"""create_payments_1

Revision ID: 0bbf59fd1b29
Revises: c9a888c20915
Create Date: 2024-07-12 04:55:22.387090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.src.infrastructure.database.models import Settings

# revision identifiers, used by Alembic.
revision: str = '0bbf59fd1b29'
down_revision: Union[str, None] = 'c9a888c20915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	op.execute("CREATE TYPE paymenttype AS ENUM ('STARS', 'CRYPTO_BOT')")

	# Создаем тип данных locale
	# Добавляем столбцы в таблицу payments
	op.add_column('payments',
				  sa.Column('payment_type', sa.Enum('STARS', 'CRYPTO_BOT', name='paymenttype'), nullable=False))
	op.add_column('payments', sa.Column('locale_payed', sa.Enum('RU', 'EN', 'DE', 'UK', name='locale'), nullable=False))
	op.alter_column('payments', 'amount',
					existing_type=sa.INTEGER(),
					type_=sa.BigInteger(),
					existing_nullable=False)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column('payments', 'amount',
					existing_type=sa.BigInteger(),
					type_=sa.INTEGER(),
					existing_nullable=False)
	op.drop_column('payments', 'locale_payed')
	op.drop_column('payments', 'payment_type')
	# ### end Alembic commands ###
