"""qwe

Revision ID: 6e59a244a53b
Revises: f37b0a7a4d08
Create Date: 2024-07-19 19:59:59.471044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e59a244a53b'
down_revision: Union[str, None] = 'f37b0a7a4d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payments_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'payments_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
