"""create_mailing_column

Revision ID: c9a888c20915
Revises: e131a4fee1af
Create Date: 2024-07-09 07:08:16.142938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a888c20915'
down_revision: Union[str, None] = 'e131a4fee1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailing', sa.Column('finish_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('payments', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('mailing', 'finish_date')
    # ### end Alembic commands ###
