"""create_payments_2

Revision ID: db4eba9362cd
Revises: 0bbf59fd1b29
Create Date: 2024-07-12 08:12:11.315454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4eba9362cd'
down_revision: Union[str, None] = '0bbf59fd1b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE paymentsstatus AS ENUM ('SUCCESS', 'PENDING', 'CANCEL')")

    # Add the new column
    op.add_column('payments', sa.Column('payments_time', sa.INTEGER(), nullable=True))

    # Alter the existing column with explicit USING clause
    op.execute("ALTER TABLE payments ALTER COLUMN status TYPE paymentsstatus USING status::paymentsstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('SUCCESS', 'PENDING', 'CANCEL', name='paymentsstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('payments', 'payments_time')
    # ### end Alembic commands ###
